---
driver_config:
  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITAL_OCEAN_API_KEY'] %>

provisioner:
  name: puppet_apply
  manifests_path: manifests
  modules_path: modules
  hiera_data_path: hieradata

platforms:
- name: centos-5.8
  driver_plugin: digital_ocean
  driver_config:
    size: 1gb
    image: centos-5-8-x64

- name: centos-6.5
  driver_plugin: digital_ocean
  driver_config:
    size: 1gb
    image: centos-6-5-x64

- name: centos-7.0
  driver_plugin: digital_ocean
  driver_config:
    size: 1gb
    image: centos-7-0-x64

suites:

- name: default
  manifests: site.pp
